spring:
  application:
    name: traffic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/traffic
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  sql:
    init:
      mode: never
#amazon:
#  s3:
#    bucket:
#      name: team486-cctvvideo
#    key:
#      access: XX
#      secret: XX
#    region: XX